### ISSUE TITLE
Parse C++ headers?

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/Adept3x#14]
Only a very limited subset of C++. For example:

https://sourceforge.net/p/iup/iup/HEAD/tree/trunk/iup/include/iup_plus.h

https://sourceforge.net/p/iup/iup/HEAD/tree/trunk/iup/include/iup_class_cbs.hpp

**Comment by iahung3** [comment]
More complex (multiple inheritance):

https://github.com/dbsoft/dwindows/blob/master/dw.hpp

**Comment by IsaacShelton** [comment]
After C headers are supported, this may be considered.

One problem though, is that C++ classes have different semantics, per-value constructors/destructors/copy-constructors/move-constructors and types such as references and r-value references, which don't currently have any equivalent in Adept.

It's not entirely clear yet how C++ classes that have a destructors/copy-constructors/move-constructors should work from Adept. They should work the same as in C++, but that would drastically complicate the semantics of the language and could greatly increase the complexity of generic code, but we have to see what the best way of doing this is
