### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/Adept3x#17]
Migrated from https://github.com/AdeptLanguage/Adept/issues/345.

For exotic platforms, you don't have to make binary releases for them in your Nightly builds. Please make sure that Adept builds and runs on the platforms is more than enough. If you can't setup the virtual machines, you can ask the community to test it for you on their systems.

**Comment by IsaacShelton** [comment]
I've done some experiments trying to dynamically interact with a qemu vm instance and have had success.

Since FreeBSD has a console-only mode, I think it should be possible.

Otherwise yes, in the worst case, the community would need to be responsible for testing it.

**Comment by IsaacShelton** [comment]
It looks like some people have figured out how to run it in a VM already https://github.com/vmactions/freebsd-vm, so it is definitely possible, although it will probably be very slow to build/test since KVM is not enabled on GitHub-hosted runners

**Comment by IsaacShelton** [comment]
FreeBSD support has been added :tada:

Automated testing/building for each platform hasn't been created yet, but it should be included in that once it happens
