### ISSUE TITLE
Cross compile to HaikuOS

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/Adept3x#20]
Haiku is not something you want to run as a daily driver (no hardware acceleration for graphics, no modern browser,...), but it's indeed an interesting platform.

**Comment by ghost** [comment]
Why do you want to add support for an OS that you don't want to use it yourself?

**Comment by IsaacShelton** [comment]
Haiku does seem to be a highly requested platform after FreeBSD.

I'm not sure what it's ABI is like though, and from what I've heard it uses C++ classes in its APIs, so I'm not sure yet how this would look like.

It might be good, but at the same time if the ABI is too bespoke/antiquated then it might not be worth it. We'll have to see.

Also native compilation for it would probably be hard enough on its own. Cross compiling might not be too bad though if it has a packaged libc and if LLVM's lld supports it.
