### ISSUE TITLE
Cross compile to illumos

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/Adept3x#21]
OmniOS, SmartOS, Tribblix,... They are a family of server oriented OS.

p/s: I don't care about Oracle Solaris since it's a closed source crap.

**Comment by ghost** [comment]
Same problem as Linux. The libraries are different between distros.

**Comment by IsaacShelton** [comment]
If they have libraries that differ between distros similar to Linux like Curculigo mentioned, then there isn't really a good way to cross-compile them.

Also, I don't know if supporting these is the highest priority at the moment, but I'll take a look into it.
