### ISSUE TITLE
Which niche markets does this language aim for?

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/Adept3x#24]
People are crazy about Rust. Rewrite in Rust is everywhere. FreeBSD people are considering adding Rust to the kernel. Linux has already did it. This language itself is written in Rust. The only language people mentioned in rewrite in Rust threads that they think could be an alternative to Rust is Zig. How can you think it can compete with Rust (or Zig)?

**Comment by IsaacShelton** [comment]
The goal is to what Rust and Zig are doing, but better.

They both have big weaknesses that we hope to fix and improve upon.

Some weak spots are:

- Allocators (in Rust)
- Generic Type Safety (in Zig)
- C support (in Rust)
- Async (in both)
- Compile-Time Evaluation (in Rust)

just to list the biggest ones
