### ISSUE TITLE
Adept in Linux kernel?

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/Adept3x#25]
<details>
<summary>Spoiler warning</summary>
Perhaps you should work on a GCC frontend now, haha 😆 
</details>

**Comment by IsaacShelton** [comment]
I personally think it would probably be more likely and profitable to build a new kernel than to try to force it into Linux. If Linux wanted to adopt it anyway, they would probably need to be the ones to implement it as a part of the GNU Compiler Collection.
