### ISSUE TITLE
Windows API

### ISSUE THREAD

**Issue by ghost** [IsaacShelton/Adept3x#9]
My attempt to parse https://github.com/marlersoft/win32json to create Adept binding failed. The reason why I decided to work with https://github.com/marlersoft/win32json is because I can't parse https://github.com/microsoft/win32metadata directly. The JSON files are too complex for me. I have tried many times but I still fail. It seems we will need another approach for the Windows API.

**Comment by IsaacShelton** [comment]
Yes the Win32 API is complex. The example repos too like https://github.com/microsoft/windows-rs/tree/master are entire projects unto themselves.

In the long run, it would be nice to figure out the manifests, but yes as you mentioned it is very complicated.

Maybe there are implementations in simpler languages which can be easily translated to emit Adept code instead.

**Comment by ghost** [comment]
What about parsing the headers directly using the built-in C preprocessor of Adept? I suggest using the MinGW headers of Windows API rather than the official Windows SDK as they are public domain.

**Comment by IsaacShelton** [comment]
That's a really good idea. We would get it all just for free without needing to translate anything
